name: 'Count lines of code'
description: 'Count the lines of code in the repo'
inputs:
  who-to-greet: #id of input
  description: 'Who to greet'
  default: 'World'
outputs:
  time:
    description: 'The time we greeted you'
runs:
    using: 'docker'
    image: Dockerfile
    args:
      - ${{ inputs.who-to-greet }}
